### ISSUE TITLE
Can't find how to properly install/tests failing

### ISSUE THREAD

**Issue by coeur-de-loup** [nut-tree/nut.js#116]
**Short summary**
npm run test fails after I install.. I can make the mouse move, but no keyboard control or anything else. I'm really new to this so I must be missing something really basic...
**Detailed question**
I'm on mac Mojave,
steps I did:
npm i @nut-tree/nut-js
npm  run audit
npm run postinstall
npm test:
error: /trailmix-master/node_modules/execa/index.js:174:9)
error: trailmix-master/node_modules/execa/index.js:278:16

I hppe this is enough details, I would greatly appreciate the help!!!

**Comment by s1hofmann** [comment]
Hi @coeur-de-loup,

I'm assuming you're running the examples contained in https://github.com/nut-tree/trailmix.
In this repo, `npm i && npm t` should be sufficient to run examples. However, these will most likely run into errors, since I built them for a Linux system.

Let me know if there are any more questions!

**Comment by s1hofmann** [comment]
Closed due to inactiviy. Feel free to re-open on any further questions

**Comment by coeur-de-loup** [comment]
Hey!!! Sorry for the delay! Thanks for the answer. Is there a way to make this work on mac or it's too complicated?

**Comment by s1hofmann** [comment]
Hi @coeur-de-loup,

yes, `nut.js` is cross-platform compatible, so it's possible to install it on a Mac.

Since you're on a Mac, could you please create a new project (`npm init -y`), install `nut.js` (`npm i @nut-tree/nut-js`) and afterwards copy the sample shown in the readme to an `index.js`?

In case prerequisites for macOS are met, you should be able to run the sample via `node index.js`.
If not, please post the error output here.

Best regards

Simon

**Comment by s1hofmann** [comment]
@coeur-de-loup Another addition, regarding accessibility permissions on macOS: https://github.com/nut-tree/nut.js/issues/133#issuecomment-626772314

**Comment by coeur-de-loup** [comment]
Hi @s1hofmann,

I managed to run the sample code after installing mocha.
The mouse started to move but then I get this error:

`Segmentation fault: 11`

So it's a mac  permission error, but I don't know what to add to the accessibility list. I tried adding the terminal itself without luck. I can't add index.js neither (it's greyed out).

any Idea?

Thanks for the help!

Andy

**Comment by s1hofmann** [comment]
Hi @coeur-de-loup,

to be honest, I still can't fully comprehend what you're trying to achieve nor which steps you're carrying out to do so.

Could you maybe provide a sample repo which allows me to reproduce your setup?

**Comment by s1hofmann** [comment]
Closed due to inactiviy. Feel free to re-open on any further questions
