### ISSUE TITLE
Extract finder to small package?

### ISSUE THREAD

**Issue by shirshak55** [nut-tree/nut.js#132]
Hi there. The package looks really great.

I would like to search image in screen but I really don't want to add whole package for single stuff? Wouldn't it be wise to have some small package that can help sitaution like this?

```
 let img = await fs.readFileSync(path.join(__dirname, "/../src/chromeDinosaur.png")) 
 let screen = robot.screen.capture().image

find(screen,img) // returns true if chromedinosaur is in screen?
```

**Comment by s1hofmann** [comment]
Hi @shirshak55,

at the moment I do not have plans to introduce additional sub packages.

> Wouldn't it be wise to have some small package that can help sitaution like this?

While it would be technically possible to separate packages, it would not have any impact on package size. Image recognition in nut.js does not only work on image data, but also requires screen information to properly handle e.g. retina displays, so in terms of required dependencies it wouldn't make any difference.

**Comment by svettwer** [comment]
Hiho :wave: 
I was curious about the exact size of nut.js. Here is what i found out while installing nut.js in a fresh npm project:

```
[sven@arch1337]: ~/tmp/node_modules>$ du -hs
167M	.
[sven@arch1337]: ~/tmp/node_modules/@nut-tree>$ du -hs
4.0M	.
[sven@arch1337]: ~/tmp/node_modules>$ find . -name "*opencv*" | xargs du -hs
141M	./opencv4nodejs-prebuilt
384K	./@nut-tree/nut-js/dist/lib/provider/opencv
```
So ~84% of nut.js is `opencv4nodejs-prebuilt` which is required for the image recognition part. So one could potentially save ~14% package size, because nut.js libs are requried as well on top of the 141M. Even if I can't estimate the effort to split the package up, I don't think that the result is worth, it no matter how few effort it may be. It would also have an impact on the effort of the release process, integration testing and so on.

**Comment by shirshak55** [comment]
hi  s1hofmann 

As it is not going to give any significant benefit i guess its not worth to change to small package.

Thanks .
