### ISSUE TITLE
Create screenshot from region

### ISSUE THREAD

**Issue by parkpaya** [nut-tree/nut.js#154]
**Short summary**
Trying to take screenshot on specific region of screen but still can't figure how

**Detailed question**
What expected
```
const {  Region ,ImageWriter,ScreenAction} = require("@nut-tree/nut-js");
ImageWriter.store(new ScreenAction.grabScreenRegion(new Region(x,y,w,h)),"myImage.png");

```
but get an error

**Comment by parkpaya** [comment]
OK, I figure it out now.

const regionCapture = async (selectedRegion,outputFilename) => {
  var regionImage =  await screen.vision.grabScreenRegion(selectedRegion);
  screen.vision.saveImage(regionImage,outputFilename);
};

regionCapture(new Region(x,y,w,h),"myImage.png");

**Comment by s1hofmann** [comment]
Hi @parkpaya,

functionality to capture screen regions is indeed missing on the `screen` public interface.
Since you already dug into it, want to contribute? Would be more than happy about a PR

**Comment by svettwer** [comment]
I recently worked with the workaround proposed by @parkpaya. It works great. :+1: It's a little ugly, because you have to grab deep into the dists for the import but it works.

As I assume, I'm not the only person who requires that feature, I'll reopen this issue and alter the public api as you suggested @s1hofmann.
