### ISSUE TITLE
Installed Electron App crashes after upgrading to 2.3.0

### ISSUE THREAD

**Issue by TrofinSorin** [nut-tree/nut.js#449]
**Version**
NutJS 2.3.0
Node 14.12.0
MacOS Catalina 10.15.7

**Short overview**
After upgrading NutJS from 2.2.1 to 2.3.0 the packaged and installed electron app crashes after running it.

**Issue occurs on**

MacOS Catalina 10.15.7

**Detailed error description**
![NutJS 2 3 0 Error](https://user-images.githubusercontent.com/43543139/200193016-3ea8447b-9046-4fa3-9e20-3ef3d7b649f6.jpg)

**Steps to reproduce error**
1. Upgrade to 2.3.0
2. Package Electron app for MacOS
3. Install the app 
4. Run the app and you will get an error and it will crash

**Comment by s1hofmann** [comment]
Hi @TrofinSorin 👋 

That's interesting. The app crashes due to a failing symbol lookup for [CGPreflightScreenCaptureAccess](https://developer.apple.com/documentation/coregraphics/3656523-cgpreflightscreencaptureaccess?language=objc), which, if you follow the link to the Apple developer docs, is supposed to be available in macOS 10.15+. (Was introduced in nut.js 2.3.0 to check required permissions on startup)

Since you're running 10.15.7, this shouldn't be a problem.

Do you have a hard requirement for this version of macOS? Or could you double check with a later version?

Best regards

Simon

**Comment by TrofinSorin** [comment]
Hello @s1hofmann, thank you for your fast answer.

I think my MacOS cannot go higher than 10.15.7 for now, it's an older MacOS.

Maybe it can be checked if the symbol exists and if does not exist instead of the crash maybe it can behave the same as 2.2.1 with no permissions on startup.

**Comment by s1hofmann** [comment]
I'll see to find a sustainable solution

**Comment by s1hofmann** [comment]
Hey @TrofinSorin 👋 

Could you give `@nut-tree/nut-js@next` a try?

**Comment by TrofinSorin** [comment]
@s1hofmann it works on @nut-tree/nut-js@next !!
