### ISSUE TITLE
The specified module could not be found

### ISSUE THREAD

**Issue by YozieB** [nut-tree/nut.js#532]
**Version**
latest
Tried node 16.13.0; 16.20.2
Tried electron 12.0.0; 12.2.3 and higher

**Short overview**
After successfull build in electron got the error, when i run in dev mode everything works fine.
**Issue occurs on**

- [ ] Virtual machine
- [ ] Docker container
- [ x] Dev/Host system

**Detailed error description**

**Steps to reproduce error**

**Additional content**
![image](https://github.com/nut-tree/nut.js/assets/80385486/3953945f-506f-4b67-a16f-eede4c52a52b)

> Please provide any (mandatory) additional data to reproduce the error (Dockerfiles etc.)

**Comment by s1hofmann** [comment]
Hi @YozieB 👋 

since everything works in dev mode and you’re only seeing this error after building, I’d guess your build process does not properly bundle native addons (opencv4nodejs.node, in this case).

Native bindings have to be included in the resulting bundle, depending on your setup, configuration may vary.

Best regards 

Simon

**Comment by YozieB** [comment]
> Hi @YozieB 👋
> 
> since everything works in dev mode and you’re only seeing this error after building, I’d guess your build process does not properly bundle native addons (opencv4nodejs.node, in this case).
> 
> Native bindings have to be included in the resulting bundle, depending on your setup, configuration may vary.
> 
> Best regards
> 
> Simon

aight thanks, gotta check build proccess
